### ISSUE TITLE
Could not resolve project :react-native-fbads.

### ISSUE THREAD

**Issue by anujec722** [callstack/react-native-fbads#251] opened 2020-06-29 01:56 UTC
Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (C:\Users\ss\swc_v3\node_modules\execa\index.js:174:9)
    at C:\Users\ss\swc_v3\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\ss\swc_v3\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\ss\swc_v3\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by btb331** [comment] 2020-07-07 07:06
I'm having the same problems

**Comment by Suraj-Tiwari** [comment] 2020-07-12 11:37
manual linking seems to be resolving this issue, please try running `react-natiave link react-native-fbads`.

**Comment by xRoGeSx** [comment] 2020-07-14 10:30
Try going into your settings.gradle in the android folder;

Change the line 

` project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads')`

To the

`project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')`

This fixed it for me. I am unsure, but I think the problem is with gradle properties of the module; It doesn't point corretly to the src directory

**Comment by iambavith** [comment] 2020-08-07 03:45
> Try going into your settings.gradle in the android folder;
> 
> Change the line
> 
> ` project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads')`
> 
> To the
> 
> `project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')`
> 
> If you don't have that line there, you should run
> 
> `react-natiave link react-native-fbads`
> 
> This fixed it for me. I am unsure, but I think the problem is with gradle properties of the module; It doesn't point corretly to the src directory

Tried this brother.. but didn't helped :(

**Comment by hussain5233** [comment] 2020-10-05 17:25
+1

**Comment by akhzarna** [comment] 2021-01-01 18:59
> manual linking seems to be resolving this issue, please try running `react-natiave link react-native-fbads`.

not helped

**Comment by akhzarna** [comment] 2021-01-01 19:00
not helped

**Comment by mrousavy** [comment] 2021-02-10 09:46
I think this will be fixed in v7 (https://github.com/callstack/react-native-fbads/pull/284)

**Closed** 2021-02-10 16:17 UTC
