### ISSUE TITLE
No Clicks and no impressions reported in the Monetization manager

### ISSUE THREAD

**Issue by pitchourou** [callstack/react-native-fbads#195] opened 2019-02-20 04:30 UTC
# Bug Report

**Before opening**

- Did you try the latest release? YES
- Did you look for existing issues? YES

**Ad Modules**

Native Ads

**Platforms**

Android

**Versions**
- react-native-fbads: 6.0.2
- react-native: 0.57

**Ads Environment**

- Facebook app installed:
- Happens in production (release build + **not** a test device):
- Facebook review status:  approved

**Current Behaviour**

No clicks or impressions reported

**Additionals**

<img width="1286" alt="capture d ecran 2019-02-19 a 23 58 57" src="https://user-images.githubusercontent.com/16292971/53066447-38112380-34d0-11e9-81a4-a595a9c1eb19.png">

**Comment by erandagan** [comment] 2019-02-20 07:51
Duplicate of #172

**Closed by erandagan** 2019-02-20 07:51 UTC
