### ISSUE TITLE
Native ads: got object with empty fields

### ISSUE THREAD

**Issue by ViraRodionova** [callstack/react-native-fbads#138] opened 2018-10-18 15:22 UTC
Hello everyone!

I have an issue with the native ads on Android.

When I ask for test ads from facebook all works great. But when I'm trying to request the live(productions) ads, always receive an object with null values.
But on iOS all works fine as for test ads, as for live ads.

Have any ideas why does it happen?

Dependencies:
* "react-native": "0.54.2"
* "react-native-fbads": "5.0.1"
* "react-native-fbsdk": "0.7.0"

Android dependencies:
* "com.facebook.android:audience-network-sdk:4.99.1"
* "com.facebook.android:facebook-android-sdk:4.+"

iOS dependencies:
* FBAudienceNetwork (4.99.3)

**Comment by erandagan** [comment] 2018-10-19 09:57
Hi there,
Few questions:

Could you please attach a sample of your usage?
Are you compiling in Dev or Release when this issue appears?
Did you submit your integration to Facebook for review?

**Comment by ViraRodionova** [comment] 2018-10-19 10:59
@erandagan 

**1) Facebook review**
Both apps (iOS, Android) are already passed review and had `Active` status

**2) Test Devices Page**
* Testing enabled -> `true`
* Use real advertiser content -> `true`
* both devices are added as test devices

**3) Facebook app**
no matter if it is installed or not

**4) Are you compiling in dev or release when this issue appears?**
Android - both

**5) Usage**

**`AdsScreen.js`**

```
...
import { getAdsManager } from '../../adsSingleton.js';
import AdComponent from './AdComponent.js';
...
<AdComponent
    adsManager       = {getAdsManager()}
    adChoicePosition = 'topRight'
    expandable       = {false}
/>
```

**`AdComponent.js`**
```
import { AdIconView, MediaView, TriggerableView, withNativeAd } from 'react-native-fbads';

class AdComponent extends Component {
    static propTypes = {
        nativeAd : PropTypes.object.isRequired
    };

    static defaultProps = {};

    render() {
        const {
            advertiserName,
            bodyText,
            callToActionText,
            headline
        } = this.props.nativeAd;

        return (
            <View style={styles.layout}>
                <MediaView style={styles.mediaView} />
                <View style={styles.advertiserContainer}>
                    <AdIconView style={styles.appIcon} />
                    <Text style={styles.advertiser} numberOfLines={2}>{advertiserName}</Text>
                </View>
                <View style={styles.descriptionContainer}>
                    <Text style={styles.description} numberOfLines={1}>{headline}</Text>
                    <Text style={styles.description} numberOfLines={1}>{bodyText}</Text>
                </View>
                <View style={styles.actionButtonContainer}>
                    <TriggerableView style={styles.actionButtonText}>
                        <Text style={styles.actionButtonText}>{callToActionText}</Text>
                    </TriggerableView>
                </View>
            </View>
        );
    }
}

export default withNativeAd(AdComponent);

```

**`adsSingleton.js`**
```
import { NativeAdsManager } from 'react-native-fbads';
...

let adsManager = new NativeAdsManager(`${config.nativePlacementId[isIOS ? 'ios' : 'android']}`, 5);

export function getAdsManager() {
    return adsManager;
}

export default getAdsManager;

```

**6) Result**
iOS - shows the real ads
Android
- receive object `nativeAd` with empty fields
- errors in logcat:
    - `E/f: Ad not loaded`
    - `E_NO_NATIVE_AD_VIEW` in JavaMethod `registerViewsForInteraction()`, but `nativeAdView` is not null.

**Comment by erandagan** [comment] 2018-10-20 10:44
Not sure why the FB SDK fails to load an ad (the `Ad not loaded` log isn't coming from this library), but we should handle that case better that's for sure (not render the ad at all and provide a failure callback).

@Suraj-Tiwari any guesses what can cause such failure in the first place?

**Comment by Suraj-Tiwari** [comment] 2018-10-20 11:34
Well, according to my information ads are showing in production, as I'm
working on resolving blurry Media image issue on production ads, production
ads are working fine. Just media is a bit blurry, but as this issue is
raised I'll check it on my side for possible issue

**Comment by Suraj-Tiwari** [comment] 2018-10-20 11:37
According to my information user must have Facebook app installed. To show
live ads

**Comment by ViraRodionova** [comment] 2018-10-22 08:42
@Suraj-Tiwari @erandagan 
I've checked the app at another devices. It work as it is described at https://developers.facebook.com/docs/audience-network/testing/ .
And I think, that all is ok now.

But using that one device, I still receive the object with empty fields.

**Comment by Suraj-Tiwari** [comment] 2018-10-22 16:49
Might be because of your device is blacklisted due to improper loading or
invalid production testing.
Please confirm with Facebook support team.

**Comment by erandagan** [comment] 2018-10-22 20:17
@Suraj-Tiwari anyway I think that this case should be handled by the library in a safer manner, invoking an error callback or passing some sort of error prop to the user's component to prevent unexpected behaviour on such cases, which can lead to crashes that are hard to trace.

**Comment by Suraj-Tiwari** [comment] 2018-10-23 18:08
@erandagan there will be no crash in case of no ads. If you have any plan we can go with it.

**Comment by erandagan** [comment] 2018-10-24 07:17
The user's code may very well crash since it does not expect to get a
native ad prop that's empty. For instance, trying to get the length of the
ad description will lead to a crash.

I'll try to look at the flow and see what we can do to prevent this.

**Comment by erandagan** [comment] 2018-11-09 08:16
@ViraRodionova Can we close this now that your PR is merged?

**Comment by Suraj-Tiwari** [comment] 2018-11-09 08:29
@erandagan tested will null response situation?

**Comment by erandagan** [comment] 2018-11-09 09:18
@Suraj-Tiwari I failed reproduce the bug, could be that it simply didn't happen or it was fixed. That's why I'm checking with @ViraRodionova who've encountered this in the first place :)

**Closed** 2018-12-22 16:56 UTC
Labels: component:native-ads
