### ISSUE TITLE
MediaView is not showing until clicks on the Screen

### ISSUE THREAD

**Issue by mahesh963** [callstack/react-native-fbads#168] opened 2018-12-04 11:48 UTC
# Bug Report

**Before opening**

- [ ] Did you try the latest release?
No
- [ ] Did you look for existing issues?
yes

**Native Ads**

**Platforms**

*Android Version

**Versions**
- react-native-fbads:^5.0.1
- react-native:0.56.0

**Ads Environment**

- Facebook app installed: Installed
- Happens in production :  released build
- Facebook review status: approved

**Current Behaviour**

I Implemented the Native Ad According to my Application. Everything is working Fine. MediaView is not showing until clicks on the Screen(At the View where Media View is placed).

![screenshot_20181204-164942_christenpro](https://user-images.githubusercontent.com/20550553/49439869-35176880-f7e8-11e8-9321-eb3453cfc05d.jpg)

**Expected Behaviour**
Expecting to Show the Media View as Slider (or) Video (or) Image Initially along with the remaining

![screenshot_20181204-164953_christenpro](https://user-images.githubusercontent.com/20550553/49439810-0c8f6e80-f7e8-11e8-9ce6-5a1ace3f82db.jpg)

**Comment by Suraj-Tiwari** [comment] 2018-12-04 11:53
Please try latest release first.
Also Share your code

**Comment by christenpro** [comment] 2018-12-04 12:53
**@Suraj-Tiwari** also getting blurred image in MediaView.

**Comment by Suraj-Tiwari** [comment] 2018-12-04 13:03
Blurred Media Image is known issue, But "Image or other media Not showing"
we haven't faced it while testing.

**Comment by mahesh963** [comment] 2018-12-11 04:15
Hi @erandagan, i'm still getting the Fix Double value crash Issue and Media View is not loading Initially

**Comment by erandagan** [comment] 2018-12-11 07:17
Did you try the version on master? I deployed the fix to a large scale
production app and it seems to work flawlessy.

**Comment by Trancever** [comment] 2018-12-11 12:17
@erandagan Should we release new minor version?

**Comment by erandagan** [comment] 2018-12-11 13:32
@Trancever Yes, that would be great 👍

**Comment by Trancever** [comment] 2018-12-11 15:24
v6.0.1 landed on npm.

**Comment by christenpro** [comment] 2018-12-12 17:30
@erandagan @Trancever Still Double value crash Issue and Media View is not loading Initially

**Comment by Suraj-Tiwari** [comment] 2018-12-12 18:09
@erandagan we should recheck it on different scenario, reason could be
android version specific.

i can test on Following Android version (physical devices):
9.0
8.0.1
7.0

**Comment by erandagan** [comment] 2018-12-12 18:15
@Trancever Did you remember to transpile to TS before publishing? I just tried installing 6.0.1 and I seem to get the old `dist`, without the bugfix.

@Suraj-Tiwari The code has been tested on >50,000 users in a production app, I don't think it has to do with the Android version.

**Comment by christenpro** [comment] 2018-12-13 04:13
@Suraj-Tiwari @erandagan @Trancever  Please check this scenario [https://jsbin.com/qeluraf/edit?output](url)

**Comment by Trancever** [comment] 2018-12-13 10:15
@erandagan Didn't do that.. We should have a script that do it before publishing.. Will release 6.0.2 with new dist.

**Comment by Trancever** [comment] 2018-12-13 10:21
Check v6.0.2 guys :)
@erandagan  Could you make an issue for that publish process ?

**Comment by christenpro** [comment] 2018-12-15 16:34
@erandagan @Trancever @Suraj-Tiwari Thank you guys... crashing fixed, But still media view doesn't display until click or scroll down/top. I don't want to display blur media view, i want to show only scroll ads and videos. Is it possible, please let me know...

**Comment by Suraj-Tiwari** [comment] 2018-12-15 16:44
Blur media view is issue within AudienceSdk
I had a talk with fb dev team, they said blurry image is a placeholder to
fill remaining space of image to keep original aspect ratio of image, but
somehow sdk is detecting image space as placeholder

ps: They aren't fixing it for react naive.

**Comment by christenpro** [comment] 2018-12-15 16:52
@Suraj-Tiwari Thank you for quick response.

What about Carousel ads display in Media View?

**Comment by Suraj-Tiwari** [comment] 2018-12-15 20:06
Those were working fine video ads too. When i tested it last time

**Comment by erandagan** [comment] 2018-12-15 21:13
@christenpro Is there a chance you're displaying the ad component within a scrolling container, such as `ScrollView` or `FlatList`? There is a known behaviour issue with scrolling components which is rooted in Facebook's SDK (so we can't fix it for now). 

Just wondering if you could test in a non-scrolling container and see what happens - I know this isn't a real solution, but this will help us if this is all part of a bigger problem.

**Comment by christenpro** [comment] 2019-03-29 10:32
@erandagan @Trancever @Suraj-Tiwari Still media view doesn't display until click or scroll down/top. Please let me know about Blur Media, I didn't get proper reply for blur view.

**Comment by dr-andy** [comment] 2019-12-02 15:30
Same problem. MediaView appears for the first seconds then disappears. It appears if I scroll the MediaView then disappears again after a few seconds. Tested on Android 8.0 device. Other components work as intended.

**Comment by paddy57** [comment] 2020-04-23 12:12
> Same problem. MediaView appears for the first seconds then disappears. It appears if I scroll the MediaView then disappears again after a few seconds. Tested on Android 8.0 device. Other components work as intended.

Did you solve this ?

**Comment by TMaszko** [comment] 2021-04-10 21:56
Please check out v7 available now ! :) if it hasn't been fixed yet then I'll reopen it.

**Closed by TMaszko** 2021-04-10 21:56 UTC
Labels: component:native-ads
