### ISSUE TITLE
App Icon removed when install package

### ISSUE THREAD

**Issue by D4m1n0** [callstack/react-native-fbads#174] opened 2018-12-14 15:26 UTC
# Bug Report

**Before opening**

- [Yes ] Did you try the latest release?
- [ Yes] Did you look for existing issues?

**Ad Modules**

Entire Package

**Platforms**

Android

**Versions**

- Android: 8.0.0
- iOS: /
- react-native-fbads: 6.0.1
- react-native: 0.57.5

**Ads Environment**

Honor View 10

**Current Behaviour**

I have got an App Icon (ic_launcher), when I follow step by step the installation of Facebook Ads (change manifest, mainApplication, etc...) Facebook ads works but there's just the basic App Icon.
(If I remove react-native-fbads, my App Icon reappear.

**Comment by a26364177** [comment] 2018-12-17 03:37
App icon was covered by react-native-fb-ads example project in node_module react-native-fb-ads folder.

**Comment by pitchourou** [comment] 2018-12-20 17:24
Same , RN 0.51 
Also getting error undefined is not a function

**Comment by abhaypai2611** [comment] 2018-12-21 17:06
Even we are facing the same issue. RN 0.57.1

**Comment by abhaypai2611** [comment] 2018-12-21 17:18
I did `yarn add react-native-fbads` and got a version number of `6.0.2` but I am unable to see any tags given for the same in this repo. I checked the beta branch and I guess the issue lies in https://github.com/callstack/react-native-fbads/blob/d179fe27f2c372261e7f9ef0bd53a34c145035c1/android/app/src/main/AndroidManifest.xml#L6

@Suraj-Tiwari : Can you kindly check and remove the app icon from the latest version?

**Comment by erandagan** [comment] 2018-12-21 18:07
You can submit a PR that removes the icons files and the launcher reference from the manifest.

**Comment by Suraj-Tiwari** [comment] 2018-12-21 18:15
Npm Release Also have example folder?

Manifest issues was already resolved in early stage of development.

**Comment by erandagan** [comment] 2018-12-21 18:16
@Suraj-Tiwari  That's odd, I believe [we have an .npmignore in place ](https://github.com/callstack/react-native-fbads/blob/master/.npmignore) to skip the example.

**Comment by Suraj-Tiwari** [comment] 2018-12-21 18:17
When Library is added using git developers face this issue. Due to conflict
with example folder.

**Comment by Suraj-Tiwari** [comment] 2018-12-21 18:31
@abhaypai2611 you are on wrong branch checkout on master
@erandagan appicon issue doesn't exist in current release of npm

**Comment by abhaypai2611** [comment] 2018-12-22 02:51
@Suraj-Tiwari && @erandagan - My bad! I was looking in the wrong branch. 

But I found out some more minor issues after `yarn add react-native-fbads`. Like the package name has changed to `suraj.tiwari.reactnativefbads`. Ideally it should have be something along the lines of `com.reactnativefbads`.
<img width="465" alt="screenshot 2018-12-22 at 7 49 40 am" src="https://user-images.githubusercontent.com/8026994/50369761-82ede800-05c0-11e9-8918-d89aa2569a13.png">
I believe it can be changed here
https://github.com/callstack/react-native-fbads/blob/master/android/app/src/main/AndroidManifest.xml

Also tags for version after `4.2.2` aren't available in the repo. 
<img width="335" alt="screenshot 2018-12-22 at 7 49 03 am" src="https://user-images.githubusercontent.com/8026994/50369769-aa44b500-05c0-11e9-95a0-afb3c4044743.png">

I'm happy to fix the issues. I'll send a PR soon.

**Comment by abhaypai2611** [comment] 2018-12-22 03:53
I've never used npm publish before but after reading [this](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d) article, I believe you can move away from `.npmignore`. It makes sense after looking at this repo as we can whitelist only a few folders and files using the `files` attribute in `package.json`

```
[
    "android",
    "ios",
    "src",
    "LICENSE",
    "README.md",
    "package.json",
    "yarn.lock",
    "images"
]
```

Also in the article there's a command `npm pack && tar -xvzf *.tgz && rm -rf package *.tgz` to check a list of files that would be published to npm. I ran it to check if the example folder was added to the package. And it isn't 😅 

I think the might be in gitignore as the files mentioned below aren't there in the respective folders whereas `ic_launcher` does exist in each one of them.  

**.gitignore**
<img width="466" alt="screenshot 2018-12-22 at 9 14 51 am" src="https://user-images.githubusercontent.com/8026994/50370346-debd6e80-05ca-11e9-8372-cb995bb37fbc.png">

**res folder in android**
<img width="309" alt="screenshot 2018-12-22 at 9 14 27 am" src="https://user-images.githubusercontent.com/8026994/50370344-dc5b1480-05ca-11e9-8fc5-9fde6554f68b.png">

I am not sure if that's what causing the issue. I'll debug this in some time. For now renaming the file name solved the issue with app icon 😆

**Comment by Suraj-Tiwari** [comment] 2018-12-22 06:52
Leave package name as it is.
You are on previous branch which is 2 years old
current branch got some breaking changes
Simply unlink previous library and use current one from npm.

**Comment by abhaypai2611** [comment] 2018-12-22 09:04
I did a `yarn install react-native-fbads` which introduced the breaking changes. I try to go down in detail to debug the issue but I think you're best suited for to resolve the issue as I am unaware of the history of this package. Awaiting for a fix.

**Comment by Suraj-Tiwari** [comment] 2018-12-22 11:41
You installed older version, using current package from version 5 there is no issue. I wonder what issue you are facing actually. Because all reported issues are related to Media Component or Adchoice Deprecation please create new project and test this library into that project or try running Example app. If you found any bug file an issue. Please provide real issues. [all known issue](https://github.com/callstack/react-native-fbads/issues)

**Comment by abhaypai2611** [comment] 2018-12-22 13:59
As I mentioned above, after executing `yarn add react-native-fbads` I got version `6.0.2` installed in my project. Post installing `react-native-fbads` when I tried building my project, the app icon was set to the [default green android icon](https://developer.android.com/studio/images/write/adaptive_icon_wizard.png). Me along with other users in this thread have faced the issue with app icon after installing this package.

I will do a test on my end as you have mentioned. But I strongly recommend you to check my comment https://github.com/callstack/react-native-fbads/issues/174#issuecomment-449542785 and perform the steps to validate if `ic_launcher` is been copied in your latest npm bundle which is version `6.0.2`.

After executing the command mentioned above to check the contents of npm package I can say that the icon `ic_launcher` gets copied along with the package. 

![screenshot 2018-12-22 at 7 06 29 pm](https://user-images.githubusercontent.com/8026994/50375019-f887a180-061c-11e9-83ef-063873666777.png)

Also check the screenshot below which clearly states that your the npm bundle that you've published contains the `ic_launcher` file.

![screenshot 2018-12-22 at 7 10 51 pm](https://user-images.githubusercontent.com/8026994/50375125-9334b000-061e-11e9-98bc-a77c0c0eed0f.png)

Finally, My question is that do you think this is the root cause of the issue that users are facing with app icon being set to default after installing the latest version of `react-native-fbads` from NPM? If it is then there is an issue with your `.gitignore` https://github.com/callstack/react-native-fbads/issues/174#issuecomment-449542785.

If not then can you try and identify the issue? I'm happy to connect with you and resolve this issue if required.

Cheers!

**Comment by pitchourou** [comment] 2018-12-22 14:06
Facing the same issue, doing `yarn add react-native-fbads` i get version 6.0.2, which removes the app icon, and also get this error on startup. I'm doing nothing but importing the Library.

<img width="536" alt="capture d ecran 2018-12-21 a 18 43 07" src="https://user-images.githubusercontent.com/16292971/50375238-9c138a80-05fa-11e9-9f86-57dcab3d99c7.png">

**Comment by abhaypai2611** [comment] 2018-12-22 15:52
It was 

```
android:icon="@mipmap/ic_launcher"
android:logo="@mipmap/ic_launcher"
```

I changed it to 

```
android:icon="@mipmap/app_icon"
android:logo="@mipmap/app_icon"
```

And my issue was resolved.

**Comment by abhaypai2611** [comment] 2018-12-22 15:54
Kindly check. 
https://github.com/callstack/react-native-fbads/blob/0198b5dc82cc1ec9b504bde25f660baae096130e/.gitignore#L51 to https://github.com/callstack/react-native-fbads/blob/0198b5dc82cc1ec9b504bde25f660baae096130e/.gitignore#L55

It should be `ic_launcher.png` not `ic_launcher_round.png`

**Comment by pitchourou** [comment] 2018-12-22 15:55
@Suraj-Tiwari thanks for your answer, but got same result.
@abhaypai2611 you bbasically changed the launcher name , not sure it is the solution , is it ?

**Comment by abhaypai2611** [comment] 2018-12-22 15:57
@pitchourou Definitely it's not the solution. A developer should be able to use the app icon of his/her choice. And usually people use `ic_launcher`. I have suggested a fix in https://github.com/callstack/react-native-fbads/issues/174#issuecomment-449579618.

**Comment by Suraj-Tiwari** [comment] 2018-12-22 16:31
@abhaypai2611 current android version also support round and square app icons according to launcher. I don't know what you're doing exactly.
 
`android:icon="@drawable/ic_launcher"` will fix the issue. **note main key is `"android:icon"` not location change it according to your actual icon location.**
If you think **copay paste will work for you** please check stackoverflow.
Current library is used in many production app including mine without any issue. 

Please file your issue on "Stackoverflow.com" if you still face any issue. Issue is within your implementation. 

@pitchourou please set android value "android:icon" and set your app icon location. It'll work without any problem. if you still have any issue please share your file structure of 
`android/app/src/main/res/`
and `AndroidManfest.xml`

**Comment by erandagan** [comment] 2018-12-22 16:53
I'll go ahead and summarize this issue:

- Currently, the package wrongfully [ships with the default launcher icons](https://github.com/callstack/react-native-fbads/tree/master/android/app/src/main/res). **A PR which removes the icons is welcome.**
- There are some other bugs related to `npmignore`. **A PR which whitelists the proper resources to ship is welcome.** [This comment](https://github.com/callstack/react-native-fbads/issues/174#issuecomment-449542785) is a good start, however note that we should ship the `dist/` folder as well (which contains transpiled TS files, see #175).
I think that with RN 0.57+ (which uses Babel 7), transpiling won't be necessary as Babel 7 natively supports TS, but for now we'll continue to support older versions as well.

If you have any other problems, please open a separate issue.

**Comment by abhaypai2611** [comment] 2018-12-22 17:32
Thanks @erandagan and @Suraj-Tiwari for the quick support.

**Closed** 2018-12-22 17:40 UTC
